"""init db

Revision ID: 71b4e282a271
Revises: 
Create Date: 2022-07-19 23:05:16.637732

"""
from alembic import op
import sqlalchemy as sa
import application


# revision identifiers, used by Alembic.
revision = '71b4e282a271'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_list_list_id'), 'list', ['list_id'], unique=True)
    op.create_index(op.f('ix_list_name'), 'list', ['name'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=1000), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], ),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('list_id', 'name'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_category_category_id'), 'category', ['category_id'], unique=True)
    op.create_index(op.f('ix_category_list_id'), 'category', ['list_id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.Enum('selection', 'number', 'text', name='itemtype'), nullable=False),
    sa.Column('selection', sa.Boolean(), nullable=False),
    sa.Column('number', application.models.SqliteNumeric(length=1000), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('category_id', 'name'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_item_category_id'), 'item', ['category_id'], unique=False)
    op.create_index(op.f('ix_item_item_id'), 'item', ['item_id'], unique=True)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_item_id'), table_name='item')
    op.drop_index(op.f('ix_item_category_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_list_id'), table_name='category')
    op.drop_index(op.f('ix_category_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_list_name'), table_name='list')
    op.drop_index(op.f('ix_list_list_id'), table_name='list')
    op.drop_table('list')
    # ### end Alembic commands ###
