"""init db

Revision ID: 940c82f14751
Revises: 
Create Date: 2020-11-15 23:01:23.409361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '940c82f14751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_table('list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('list_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_list_name'), 'list', ['name'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('name', 'category_id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_item_category_id'), 'item', ['category_id'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_table('list_category',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], ),
    sa.PrimaryKeyConstraint('list_id', 'category_id')
    )
    op.create_index(op.f('ix_list_category_category_id'), 'list_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_list_category_list_id'), 'list_category', ['list_id'], unique=False)
    op.create_table('list_item',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['list.list_id'], ),
    sa.PrimaryKeyConstraint('list_id', 'item_id')
    )
    op.create_index(op.f('ix_list_item_item_id'), 'list_item', ['item_id'], unique=False)
    op.create_index(op.f('ix_list_item_list_id'), 'list_item', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_item_list_id'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_item_id'), table_name='list_item')
    op.drop_table('list_item')
    op.drop_index(op.f('ix_list_category_list_id'), table_name='list_category')
    op.drop_index(op.f('ix_list_category_category_id'), table_name='list_category')
    op.drop_table('list_category')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_category_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_list_name'), table_name='list')
    op.drop_table('list')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
